### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by samuelrvg** [Zemke/react-native-peerjs#1]
Sugestion:

Rename repository at react-native-webrtc-peerjs or react-native-peerjs-webrtc

**Comment by Zemke** [comment]
Why?

**Comment by samuelrvg** [comment]
just a suggestion for clarity

**Comment by Zemke** [comment]
Appreciating your input.

The idea is that this repository is basically [PeerJS](https://github.com/peers/peerjs) for React Native.
