### ISSUE TITLE
Error while sending message when i am the creator of the connection. 

### ISSUE THREAD

**Issue by akshaya-rao-s** [Zemke/react-native-peerjs#11]
When I create a connection and the other peer joins, the owned data connection throws error sons send()
![Screen Shot 2020-05-26 at 7 37 01 PM-1](https://user-images.githubusercontent.com/58470211/82973138-46fc5500-9ff4-11ea-9e21-e2510f617e94.png)
` peerInitiator.on('connection', async dataConnection => {
         dataConnection.on('open', () => {
               dataConnection.on('data', this.handleData);
               dataConnection.send({
               name: this.userName ? this.userName : 'Anonymous User'
             });
          });
      });`

**Comment by Zemke** [comment]
Please refer to PeerJS for this error as this repo uses their implementation only with a few changes detailed [here](https://github.com/Zemke/react-native-peerjs/blob/master/decoupling.diff) to make it work without a Browser.

You'll be well-advised to reproduce it in a Browser for them.
