### ISSUE TITLE
Cross Platform is not working

### ISSUE THREAD

**Issue by ghost** [Zemke/react-native-peerjs#14]
Cross platform is not working. It gives me the error "**Error: Negotiation of connection to remote-1602154102436 failed.**"

Peers are generating successfully but peers are not connected in cross platform.

Android to IOS and IOS to Android are not working but the same platform is working fine(Android to Android and IOS to IOS).

Is this library are  supported for cross platform connection?

Please check below screenshot

![P2PIssue_LI](https://user-images.githubusercontent.com/72555134/95482902-3e595980-09ac-11eb-80d0-8601f002d227.jpg)

please help me

**Comment by Zemke** [comment]
The issue is not related to this repository. You might refer to peers/peerjs.
