### ISSUE TITLE
PeerServer.on('open') Not Working inside Function 

### ISSUE THREAD

**Issue by jaferi512** [Zemke/react-native-peerjs#15]
I'm trying to connect to my own Peerjs Server and I want to call PeerServer.on Inside th Function But It's Not Working.
Code:
const peerServer = new Peer(undefined, {
  config: {iceServers: [{url: 'stun:stun.l.google.com:19302'}]},
  host: '172.16.1.38',
  port: 9000,
  secure: false,
  path: '/mypeer',
});

export const joinRoom = (stream) => async (dispatch) => {
  console.log('Running' + stream);
  await peerServer.on('open', function (id) {
    console.log('My peer ID is: ' + id);
  })
}

**Comment by adekunle11** [comment]
I'm facing this issue.
Using metro to test, when i open the video call page, `peerServer.on('open')` isn't called, but when i make changes to the code and save them, thereby causing the page to refresh, `peerServer.on('open')` is called
```
`
export const joinRoom = (stream) => async (dispatch) => {
    console.log('joined room')
    const roomID = 'kfjnffjfdiksjnnjjnn';
    //set my own stream
    dispatch({type: MY_STREAM, payload: stream})

    //Open a connection to our server
    peerServer.on('open', (userId) => {
        Alert.alert("peer open " + userId)
        socket.emit('join-room', {userId, roomID})
    })

    socket.on('user-connected', (userId) => {
        Alert.alert('user connected')
        connectToNewUser(userId, stream, dispatch)
    })

    // Receive a call
    peerServer.on('call', (call) => {
        call.answer(stream)

        //stream back the call

        call.on('stream', (stream) => {
            dispatch({type: ADD_STREAM, payload: stream})
        })
    })
};
`
```

`"react-native-peerjs": "^1.0.4"`,

**Comment by adekunle11** [comment]
@jaferi512 There was an issue with my code, it works.
I'm guessing you used on of the tutorials on youtube, probably the same as mine
If you did and you still have this issue, tell me so I can show you where its coming from

**Comment by angelop11** [comment]
how did you fix it? @adekunle11

**Comment by adekunle11** [comment]
> how did you fix it? @adekunle11

Share your code here
