### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by NielsDom** [Zemke/react-native-peerjs#2]
Hi, please could you add an example about how to work with react native web rtc?
In PeerJS I see calling methods but not in your code.

Does it mean we have to use PeerJS for its websocket functionality and integrate react native web rtc by ourselves?  

An integrated minimalistic example with sending/receiving a call with react native web rtc would be very nice, Thanks.

**Comment by Zemke** [comment]
There’s an example in the README.

**Comment by Ponao** [comment]
> В README есть пример.

Hi, you have no example using react-native-webrtc

**Comment by Zemke** [comment]
https://github.com/Zemke/react-native-peerjs#usage

**Comment by Ponao** [comment]
![image](https://user-images.githubusercontent.com/40126859/71325464-cac28a80-2506-11ea-9887-91e41979b71a.png)
Maybe I have something wrong, but I have no example using react-native-webrtc

**Comment by Zemke** [comment]
This is using `react-native-webrtc` under the hood.

**Comment by Ponao** [comment]
Oh well, you could not show an example using mediaConnection.on ('stream'), is there any problem with this, this event does not work for me, at least if the stream comes from the browser, thanks for your quick answers

**Comment by Ponao** [comment]
I created a new issue for this problem

**Comment by Zemke** [comment]
Well yeah, then this is a bug.

**Comment by Ponao** [comment]
How can this be fixed, or is this a bug in my code?

**Comment by Zemke** [comment]
I don't know. One would need to debug this.

**Comment by Ponao** [comment]
Can I somehow help with this?

**Comment by Ponao** [comment]
Could there be a reason that there is no addStream and onaddstream API?

**Comment by Ponao** [comment]
> I don't know. One would need to debug this.

Hi again, I just tried using the `peerjs` library, at the beginning of the script I imported `react-native-webrtc`, it worked, but the `mediaConnection.on('stream')` events still do not work, I'm trying to find a solution to this problem, but I I'm afraid I can’t handle it, because I don’t have so much experience with WebRTC, I would be very happy and grateful for any help.
