### ISSUE TITLE
Error: Unknown named module "react-native-webrtc"

### ISSUE THREAD

**Issue by samuelfruhauf** [Zemke/react-native-peerjs#22]
I'm facing a complex error when import react-native-peerjs module to any file in React native project. I just tried everything, but nothing works. Can you help me?
That is the error.

Error: Unknown named module "react-native-webrtc"

This is the step-by-step if you wanna try.

npx react-native init teste

yarn add react-native-webrtc

cd ios && pod install

cd ..

yarn add react-native-peerjs

npx react-native run-ios

import Peer from 'react-native-peerjs'

**Comment by cruzlutor** [comment]
Same issue here, any news about this?

**Comment by samuelfruhauf** [comment]
https://stackoverflow.com/questions/67307640/error-unknown-named-module-react-native-webrtc-when-imports-peerjs-module/67316466#67316466

> Same issue here, any news about this?
