### ISSUE TITLE
 Module `react-native-webrtc` does not exist in the Haste module map

### ISSUE THREAD

**Issue by hg5734** [Zemke/react-native-peerjs#3]
import Peer from 'react-native-peerjs';
I had imported the above module and this error is coming 

 bundling failed: Error: Unable to resolve module `react-native-webrtc` from `/Users/himanshu/project/node_modules/react-native-peerjs/dist/react-native-peerjs.js`: Module `react-native-webrtc` does not exist in the Haste module map

can you tell how to fix this ?

**Comment by embeddedio** [comment]
for me i just install react-native-webrtc

**Comment by hg5734** [comment]
yes right after installation 

ReferenceError: Can't find variable: location 

This error is coming

**Comment by hg5734** [comment]
This error is also is coming

**Comment by embeddedio** [comment]
i have it also it's about https i think, you need to change the src code inside node_modules->react-native-peerjs->dist->react-native-peerjs.js and search for location and remove the line.
this solution is temporary the time they fix the bug.

**Comment by hg5734** [comment]
@embeddedio @Zemke  do you guys have any solution for [Error: The current browser does not support WebRTC] ?

**Comment by embeddedio** [comment]
for me just install react-native-webrtc and remove installed app on android and rebuild

**Comment by Zemke** [comment]
`react-native-peerjs` requires you to install `react-native-webrtc` the way it’s described there.
