### ISSUE TITLE
Unable to connect to my server

### ISSUE THREAD

**Issue by thedevxen** [Zemke/react-native-peerjs#5]
Hi, I am running a local Peer JS server on my computer. When I try to connect to my server using 
react-native=peerjs it returns an error,  `ReferrenceError: Can't find variable: location`

Code:
```js
this.peer = new Peer('some-id', {
      host: 'http://192.168.0.12',
      port: 7900,
      path: '/'
 });
```

**Comment by Ponao** [comment]
Hey, you use https? If yes, you need write to 
`this.peer = new Peer('some-id', {
      host: '192.168.0.12',
      secure: true,
      port: 7900,
      path: '/'
 });`

if not

`this.peer = new Peer('some-id', {
      host: '192.168.0.12',
      secure: false,
      port: 7900,
      path: '/'
 });`

**Comment by Zemke** [comment]
Thanks for the answer, @Ponao. Closing this as there's no further feedback.
